services:
    dynamodb:
        container_name: dynamodb
        image: "amazon/dynamodb-local:latest"
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
        ports:
            - "8000:8000"
        volumes:
            - dynamodb_data:/home/dynamodb_data/data
        working_dir: /home/dynamodb_data

volumes:
    dynamodb_data:
