services:
    mongo:
        image: mongo:7.0.22
        container_name: mongo-single-rs
        restart: always
        ports:
            - "27017:27017"
        command: >
            bash -c "
              mongod --replSet rs0 --bind_ip_all &
              sleep 5 &&
              mongosh --eval '
                try {
                  rs.initiate({
                    _id: \"rs0\",
                    members: [{ _id: 0, host: \"localhost:27017\" }]
                  })
                } catch (e) {
                  print(e)
                }
              ' &&
              wait
            "
        volumes:
            - ./docker-data/mongo_data:/data/db/
        # environment:
        #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
