services:
    mongo:
        container_name: mongo
        image: mongo:8
        # restart: always
        ports:
            - 27017:27017
        volumes:
            - mongo_data:/data/db/
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    # Disabled Because running running replica-set require key file for auth
    # # For Single Node Replica set
    # mongo_rs:
    #     container_name: mongo_rs
    #     image: mongo:8
    #     restart: always
    #     ports:
    #         - 27017:27017
    #     command: >
    #         bash -c "
    #           mongod --replSet rs0 --bind_ip_all &
    #           sleep 5 &&
    #           mongosh --eval '
    #             try {
    #               rs.initiate({
    #                 _id: \"rs0\",
    #                 members: [{ _id: 0, host: \"localhost:27017\" }]
    #               })
    #             } catch (e) {
    #               print(e)
    #             }
    #           ' &&
    #           wait
    #         "
    #     volumes:
    #         - mongo_rs_data:/data/db/
    #     # environment:
    #     #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #     #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    # # For Multi Node Replica Set

    # mongo_rs_1:
    #     container_name: mongo_rs_1
    #     image: mongo:8
    #     restart: always
    #     ports:
    #         - "27017:27017"
    #     volumes:
    #         - mongo_rs_1_data:/data/db
    #     # By Adding User Name and Password MongoDB require keyFile for inner node communication
    #     # environment:
    #     #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #     #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #     command:
    #         - mongod
    #         - --bind_ip_all
    #         - --replSet
    #         - dbrs

    # mongo_rs_2:
    #     container_name: mongo_rs_2
    #     image: mongo:8
    #     restart: always
    #     ports:
    #         - "27018:27017"
    #     volumes:
    #         - mongo_rs_2_data:/data/db
    #     # environment:
    #     #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #     #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #     command:
    #         - mongod
    #         - --bind_ip_all
    #         - --replSet
    #         - dbrs

    # mongo_rs_3:
    #     container_name: mongo_rs_3
    #     image: mongo:8
    #     restart: always
    #     ports:
    #         - "27019:27017"
    #     volumes:
    #         - mongo_rs_3_data:/data/db
    #     # environment:
    #     #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #     #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    #     command:
    #         - mongod
    #         - --bind_ip_all
    #         - --replSet
    #         - dbrs

    # mongo_rs_init:
    #     image: mongo:8
    #     depends_on:
    #         - mongo_rs_1
    #         - mongo_rs_2
    #         - mongo_rs_3
    #     volumes:
    #         - ./scripts/rs-init.sh:/scripts/rs-init.sh:ro
    #     entrypoint: ["/bin/bash", "/scripts/rs-init.sh"]

volumes:
    mongo_data:
    # mongo_rs_data:
    # mongo_rs_1_data:
    # mongo_rs_2_data:
    # mongo_rs_3_data:
